language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
#before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq liblzo2-dev
install:
  - pip install codecov
  - pip install .
script: pytest
after_success:
  - codecov
